version: '2'
services:
    jhipsterelasticsearchsample-app:
        image: jhipsterelasticsearchsample
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterelasticsearchsample-mysql:3306/jhipsterelasticsearchsample?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipsterelasticsearchsample-elasticsearch:9300
        ports:
            - 8080:8080
    jhipsterelasticsearchsample-mysql:
        extends:
            file: mysql.yml
            service: jhipsterelasticsearchsample-mysql
    jhipsterelasticsearchsample-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipsterelasticsearchsample-elasticsearch
